# Generated by Django 5.2.1 on 2025-08-22 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0003_slotdatamodel'),
        ('mainapp', '0006_remove_patient_bed_id_remove_patient_room_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='room',
        ),
        migrations.AddField(
            model_name='patient',
            name='slot_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_assigned', to='bed_data.slotdatamodel'),
        ),
    ]
