# Generated by Django 5.2.1 on 2025-08-23 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0003_slotdatamodel'),
        ('mainapp', '0007_remove_patient_bed_remove_patient_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slot_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_assigned', to='bed_data.slotdatamodel', unique=True),
        ),
    ]
