# Generated by Django 5.2.1 on 2025-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_patient_slot_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
