# Generated by Django 5.2.1 on 2025-09-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalIpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ip_add', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
