# Generated by Django 5.2.1 on 2025-09-12 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0008_remove_roompositionmodel_entry_point_and_more'),
        ('mainapp', '0011_alerthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slot_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_assigned', to='bed_data.slotdatamodel'),
        ),
    ]
