# Generated by Django 5.2.1 on 2025-09-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_patient_slot_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthistory',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='is_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='is_timed_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='not_me',
            field=models.BooleanField(default=False),
        ),
    ]
