# Generated by Django 5.2.1 on 2025-09-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alerthistory_is_cancelled_alerthistory_is_help_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthistory',
            name='is_patient_pop',
            field=models.BooleanField(default=False),
        ),
    ]
