# Generated by Django 5.2.1 on 2025-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alerthistory_is_patient_pop'),
    ]

    operations = [
        migrations.AddField(
            model_name='localipmodel',
            name='port',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
