# Generated by Django 5.2.1 on 2025-09-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomanagementmodel',
            name='video_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
