# Generated by Django 5.2.1 on 2025-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0002_alter_videomanagementmodel_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomanagementmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
