# Generated by Django 5.2.1 on 2025-09-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0003_alter_videomanagementmodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomanagementmodel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='videomanagementmodel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
