# Generated by Django 5.2.1 on 2025-09-01 06:28

import video_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0004_alter_videomanagementmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomanagementmodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=video_management.models.video_upload_to),
        ),
    ]
