# Generated by Django 5.2.1 on 2025-09-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0005_alter_videomanagementmodel_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomanagementmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='videomanagementmodel',
            name='order',
        ),
    ]
