# Generated by Django 5.2.1 on 2025-09-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0006_alter_videomanagementmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomanagementmodel',
            name='video_name',
            field=models.CharField(max_length=20),
        ),
    ]
