# Generated by Django 5.2.1 on 2025-09-15 05:30

import video_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0007_alter_videomanagementmodel_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomanagementmodel',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='videomanagementmodel',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videomanagementmodel',
            name='is_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videomanagementmodel',
            name='video_image_file',
            field=models.FileField(blank=True, null=True, upload_to=video_management.models.video_upload_to),
        ),
        migrations.AddField(
            model_name='videomanagementmodel',
            name='video_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
