# Generated by Django 5.2.1 on 2025-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_rounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledslots',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
