# Generated by Django 5.2.1 on 2025-09-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_rounds', '0002_alter_scheduledslots_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchschedulemodel',
            name='trigger_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
