# Generated by Django 5.2.6 on 2025-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_rounds', '0003_alter_batchschedulemodel_trigger_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledslots',
            name='row_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
