# Generated by Django 5.2.6 on 2025-09-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_rounds', '0004_scheduledslots_row_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledslots',
            name='row_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
