# Generated by Django 5.2.6 on 2025-09-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_rounds', '0005_alter_scheduledslots_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledslots',
            name='schedule_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
