# Generated by Django 5.2.6 on 2025-09-29 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0008_remove_roompositionmodel_entry_point_and_more'),
        ('schedule_rounds', '0006_scheduledslots_schedule_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_successful', models.BooleanField(default=False)),
                ('is_attended', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('is_timeout', models.BooleanField(default=False)),
                ('not_patient', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_scheduler_batches', to='schedule_rounds.batchschedulemodel')),
                ('bed_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_scheduler_bed_data', to='bed_data.beddatamodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_scheduler_created', to=settings.AUTH_USER_MODEL)),
                ('room_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_scheduler_room_data', to='bed_data.roomdatamodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_scheduler_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
