# Generated by Django 5.2.1 on 2025-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_battery', models.CharField(max_length=100, unique=True)),
                ('robot_break', models.BooleanField(default=True)),
                ('robot_emergency', models.BooleanField(default=False)),
                ('robot_map', models.BooleanField(default=False)),
                ('robot_door_opening', models.BooleanField(default=False)),
                ('robot_door_closing', models.BooleanField(default=False)),
            ],
        ),
    ]
