# Generated by Django 5.2.1 on 2025-09-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robottelemetry',
            name='robot_map',
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_in_dock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_map_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robottelemetry',
            name='robot_battery',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
