# Generated by Django 5.2.1 on 2025-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0002_remove_robottelemetry_robot_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottelemetry',
            name='latest_bed_reached',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='latest_room_reached',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='maintenance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='maintenance_limit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='maintenance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_audio_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_battery_name',
            field=models.TextField(default='Med Bot'),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='working_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
