# Generated by Django 5.2.1 on 2025-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0003_robottelemetry_latest_bed_reached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robottelemetry',
            name='robot_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robottelemetry',
            name='robot_in_dock',
            field=models.BooleanField(default=True),
        ),
    ]
