# Generated by Django 5.2.1 on 2025-09-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0004_alter_robottelemetry_robot_break_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robottelemetry',
            name='robot_battery_name',
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_name',
            field=models.TextField(default='Med Bot'),
        ),
    ]
