# Generated by Django 5.2.1 on 2025-09-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0005_remove_robottelemetry_robot_battery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_image_file',
            field=models.FileField(blank=True, null=True, upload_to='stcm_image'),
        ),
    ]
