# Generated by Django 5.2.1 on 2025-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0006_robottelemetry_robot_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robottelemetry',
            name='latest_bed_reached',
            field=models.TextField(blank=True, default='bed_0', null=True),
        ),
        migrations.AlterField(
            model_name='robottelemetry',
            name='latest_room_reached',
            field=models.TextField(blank=True, default='room_0', null=True),
        ),
    ]
