# Generated by Django 5.2.1 on 2025-09-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0007_alter_robottelemetry_latest_bed_reached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robottelemetry',
            name='latest_bed_reached',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robottelemetry',
            name='latest_room_reached',
            field=models.CharField(blank=True, null=True),
        ),
    ]
