# Generated by Django 5.2.1 on 2025-09-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0008_alter_robottelemetry_latest_bed_reached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robottelemetry',
            name='robot_name',
            field=models.CharField(default='Med Bot'),
        ),
    ]
