# Generated by Django 5.2.1 on 2025-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0009_alter_robottelemetry_robot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmEndpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(default='Med Bot')),
                ('robot_battery', models.IntegerField(default=0, max_length=100)),
                ('robot_break', models.BooleanField(default=False)),
                ('robot_emergency', models.BooleanField(default=False)),
                ('robot_in_dock', models.BooleanField(default=True)),
                ('robot_audio_level', models.IntegerField(default=0)),
                ('robot_map_file', models.FileField(blank=True, null=True, upload_to='')),
                ('robot_map_url', models.URLField(blank=True, null=True)),
                ('robot_image_file', models.FileField(blank=True, null=True, upload_to='stcm_image')),
                ('robot_door_opening', models.BooleanField(default=False)),
                ('robot_door_closing', models.BooleanField(default=False)),
                ('latest_room_reached', models.CharField(blank=True, null=True)),
                ('latest_bed_reached', models.CharField(blank=True, null=True)),
                ('maintenance_start_date', models.DateField(blank=True, null=True)),
                ('maintenance_end_date', models.DateField(blank=True, null=True)),
                ('maintenance_limit', models.TimeField(blank=True, null=True)),
                ('working_time', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
