# Generated by Django 5.2.1 on 2025-09-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0010_armendpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j1', models.FloatField(default=0.0)),
                ('j2', models.FloatField(default=0.0)),
                ('j3', models.FloatField(default=0.0)),
                ('j4', models.FloatField(default=0.0)),
                ('j5', models.FloatField(default=0.0)),
                ('j6', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='JointPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j1', models.FloatField(default=0.0)),
                ('j2', models.FloatField(default=0.0)),
                ('j3', models.FloatField(default=0.0)),
                ('j4', models.FloatField(default=0.0)),
                ('j5', models.FloatField(default=0.0)),
                ('j6', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='JointVelocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j1', models.FloatField(default=0.0)),
                ('j2', models.FloatField(default=0.0)),
                ('j3', models.FloatField(default=0.0)),
                ('j4', models.FloatField(default=0.0)),
                ('j5', models.FloatField(default=0.0)),
                ('j6', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='latest_bed_reached',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='latest_room_reached',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='maintenance_end_date',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='maintenance_limit',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='maintenance_start_date',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_audio_level',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_battery',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_break',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_door_closing',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_door_opening',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_emergency',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_image_file',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_in_dock',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_map_file',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_map_url',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='robot_name',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='status',
        ),
        migrations.RemoveField(
            model_name='armendpose',
            name='working_time',
        ),
        migrations.AddField(
            model_name='armendpose',
            name='rx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='armendpose',
            name='ry',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='armendpose',
            name='rz',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='armendpose',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='armendpose',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='armendpose',
            name='z',
            field=models.FloatField(default=0.0),
        ),
    ]
