# Generated by Django 5.2.1 on 2025-09-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0011_jointeffort_jointposition_jointvelocity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robottelemetry',
            name='robot_battery',
            field=models.IntegerField(default=0),
        ),
    ]
