# Generated by Django 5.2.1 on 2025-09-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0012_alter_robottelemetry_robot_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='armendpose',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jointeffort',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jointposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jointvelocity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
