# Generated by Django 5.2.1 on 2025-09-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0013_armendpose_updated_at_jointeffort_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottelemetry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
