# Generated by Django 5.2.1 on 2025-09-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0014_robottelemetry_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrl_mode', models.CharField(blank=True, max_length=50)),
                ('arm_status', models.CharField(blank=True, max_length=50)),
                ('mode_feed', models.CharField(blank=True, max_length=50)),
                ('teach_mode', models.CharField(blank=True, max_length=50)),
                ('motion_status', models.CharField(blank=True, max_length=50)),
                ('trajectory_num', models.CharField(blank=True, max_length=20)),
                ('arm_number', models.CharField(default='1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GripperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_too_low', models.CharField(blank=True, max_length=50)),
                ('motor_overheating', models.CharField(blank=True, max_length=50)),
                ('driver_overcurrent', models.CharField(blank=True, max_length=50)),
                ('driver_overheating', models.CharField(blank=True, max_length=50)),
                ('sensor_status', models.CharField(blank=True, max_length=50)),
                ('driver_error_status', models.CharField(blank=True, max_length=50)),
                ('driver_enable_status', models.CharField(blank=True, max_length=50)),
                ('homing_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gripper', to='robot_management.armstatus')),
            ],
        ),
        migrations.CreateModel(
            name='JointStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_number', models.CharField(max_length=10)),
                ('limit', models.CharField(blank=True, max_length=50)),
                ('comms', models.CharField(blank=True, max_length=50)),
                ('motor', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joints', to='robot_management.armstatus')),
            ],
        ),
    ]
