# Generated by Django 5.2.1 on 2025-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0015_armstatus_gripperstatus_jointstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armstatus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gripperstatus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jointstatus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
