# Generated by Django 5.2.1 on 2025-09-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0016_alter_armstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armstatus',
            name='driver_enable_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='driver_error_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='driver_overcurrent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='driver_overheating',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='homing_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='motor_overheating',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='sensor_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='voltage_too_low',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='GripperStatus',
        ),
    ]
