# Generated by Django 5.2.1 on 2025-09-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0017_armstatus_driver_enable_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armstatus',
            name='arm_status_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='ctrl_mode_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='driver_enable_status_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='driver_error_status_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='driver_overcurrent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='driver_overheating_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='homing_status_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='mode_feed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='motion_status_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='motor_overheating_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='sensor_status_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='teach_mode_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='trajectory_num_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armstatus',
            name='voltage_too_low_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
