# Generated by Django 5.2.1 on 2025-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0018_armstatus_arm_status_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
