# Generated by Django 5.2.1 on 2025-09-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0019_alter_armstatus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointstatus',
            name='comms_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jointstatus',
            name='limit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jointstatus',
            name='motor_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='armstatus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jointstatus',
            name='arm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='joints', to='robot_management.armstatus'),
        ),
        migrations.AlterField(
            model_name='jointstatus',
            name='joint_number',
            field=models.CharField(choices=[('1', 'Joint 1'), ('2', 'Joint 2'), ('3', 'Joint 3'), ('4', 'Joint 4'), ('5', 'Joint 5')], max_length=1),
        ),
    ]
