# Generated by Django 5.2.1 on 2025-09-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0020_jointstatus_comms_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointstatus',
            name='arm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joints', to='robot_management.armstatus'),
        ),
    ]
