# Generated by Django 5.2.1 on 2025-09-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0021_alter_jointstatus_arm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointstatus',
            name='arm',
        ),
        migrations.AlterField(
            model_name='armstatus',
            name='arm_number',
            field=models.IntegerField(default=1),
        ),
    ]
