# Generated by Django 5.2.6 on 2025-09-19 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0022_remove_jointstatus_arm_alter_armstatus_arm_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottelemetry',
            name='volume',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
