# Generated by Django 5.2.6 on 2025-09-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0023_robottelemetry_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robottelemetry',
            name='robot_audio_level',
        ),
    ]
