# Generated by Django 5.2.6 on 2025-09-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0024_remove_robottelemetry_robot_audio_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottelemetry',
            name='batch_refresh_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
    ]
