# Generated by Django 5.2.6 on 2025-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0026_failedscheduledmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedscheduledmodel',
            name='reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
