# Generated by Django 5.2.7 on 2025-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0027_alter_failedscheduledmodel_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField(default=0.0)),
                ('voltage', models.FloatField(default=0.0)),
                ('current', models.FloatField(default=0.0)),
                ('power', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('time_left', models.FloatField(default=0.0)),
                ('count', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_is_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_power_stage',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_sleep_mode',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='robottelemetry',
            name='robot_in_dock',
            field=models.BooleanField(default=False),
        ),
    ]
