# Generated by Django 5.2.7 on 2025-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0028_batterystatus_robottelemetry_robot_is_charging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterystatus',
            name='charge',
            field=models.CharField(default=0.0),
        ),
        migrations.AlterField(
            model_name='batterystatus',
            name='count',
            field=models.CharField(default=0.0),
        ),
        migrations.AlterField(
            model_name='batterystatus',
            name='current',
            field=models.CharField(default=0.0),
        ),
        migrations.AlterField(
            model_name='batterystatus',
            name='power',
            field=models.CharField(default=0.0),
        ),
        migrations.AlterField(
            model_name='batterystatus',
            name='temperature',
            field=models.CharField(default=0.0),
        ),
        migrations.AlterField(
            model_name='batterystatus',
            name='time_left',
            field=models.CharField(default=0.0),
        ),
        migrations.AlterField(
            model_name='batterystatus',
            name='voltage',
            field=models.CharField(default=0.0),
        ),
    ]
