# Generated by Django 5.2.7 on 2025-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0029_alter_batterystatus_charge_alter_batterystatus_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=255, unique=True)),
                ('robot_map_file', models.FileField(blank=True, null=True, upload_to='')),
                ('robot_map_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='robottelemetry',
            name='robot_map_file',
        ),
        migrations.RemoveField(
            model_name='robottelemetry',
            name='robot_map_url',
        ),
    ]
