# Generated by Django 5.2.7 on 2025-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0030_mapmanagement_remove_robottelemetry_robot_map_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmanagement',
            name='robot_map_file',
            field=models.FileField(blank=True, null=True, upload_to='robot_maps/'),
        ),
    ]
