# Generated by Django 5.2.7 on 2025-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0031_alter_mapmanagement_robot_map_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmanagement',
            name='robot_map_image_file',
            field=models.FileField(blank=True, null=True, upload_to='robot_maps_image/'),
        ),
    ]
