# Generated by Django 5.2.7 on 2025-10-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0032_mapmanagement_robot_map_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmanagement',
            name='robot_map_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
