# Generated by Django 5.2.7 on 2025-10-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0033_mapmanagement_robot_map_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_physical_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
