# Generated by Django 5.2.7 on 2025-10-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0034_robottelemetry_robot_physical_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j1', models.FloatField(default=0.0)),
                ('j2', models.FloatField(default=0.0)),
                ('j3', models.FloatField(default=0.0)),
                ('j4', models.FloatField(default=0.0)),
                ('j5', models.FloatField(default=0.0)),
                ('j6', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
