# Generated by Django 5.2.8 on 2025-12-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_management', '0035_jointheat'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottelemetry',
            name='robot_qvalue',
            field=models.IntegerField(default=0),
        ),
    ]
