# Generated by Django 5.2.1 on 2025-08-23 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0003_slotdatamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdatamodel',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdatamodel',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdatamodel',
            name='yaw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RoomPositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_point', models.FloatField(blank=True, null=True)),
                ('entry_point_x', models.FloatField(blank=True, null=True)),
                ('entry_point_y', models.FloatField(blank=True, null=True)),
                ('entry_point_yaw', models.FloatField(blank=True, null=True)),
                ('exit_point', models.FloatField(blank=True, null=True)),
                ('exit_point_x', models.FloatField(blank=True, null=True)),
                ('exit_point_y', models.FloatField(blank=True, null=True)),
                ('exit_point_yaw', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_single_created', to=settings.AUTH_USER_MODEL)),
                ('room_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_single_data', to='bed_data.roomdatamodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_single_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room_name',), name='unique_room_slot')],
            },
        ),
    ]
