# Generated by Django 5.2.1 on 2025-08-26 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0004_slotdatamodel_x_slotdatamodel_y_slotdatamodel_yaw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdatamodel',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='roomdatamodel',
            unique_together={('room_name', 'created_by')},
        ),
    ]
