# Generated by Django 5.2.1 on 2025-08-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0005_alter_roomdatamodel_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdatamodel',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
