# Generated by Django 5.2.1 on 2025-08-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0006_alter_roomdatamodel_room_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomdatamodel',
            unique_together=set(),
        ),
    ]
