# Generated by Django 5.2.1 on 2025-08-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0007_alter_roomdatamodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompositionmodel',
            name='entry_point',
        ),
        migrations.RemoveField(
            model_name='roompositionmodel',
            name='exit_point',
        ),
    ]
