# Generated by Django 5.2.8 on 2025-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0008_remove_roompositionmodel_entry_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beddatamodel',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
