# Generated by Django 5.2.1 on 2025-09-02 08:58

import django.db.models.deletion
import vitals_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0010_localipmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bp2CheckMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys', models.CharField(blank=True, max_length=20, null=True)),
                ('dia', models.CharField(blank=True, max_length=20, null=True)),
                ('map', models.CharField(blank=True, max_length=20, null=True)),
                ('pulse_rate_note', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to=vitals_management.models.image_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('data_time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_management_created_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp2_check_me_patient', to='mainapp.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_management_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
