# Generated by Django 5.2.1 on 2025-09-10 13:15

import vitals_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bp2checkmemodel',
            name='camera_image_file',
            field=models.FileField(blank=True, null=True, upload_to=vitals_management.models.camera_image_upload_to),
        ),
        migrations.AddField(
            model_name='bp2checkmemodel',
            name='camera_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
