# Generated by Django 5.2.8 on 2025-12-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals_management', '0002_bp2checkmemodel_camera_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bp2checkmemodel',
            name='pulse_rate_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
